// pinrail-plugin/templates/vue/src/App.vue
<!-- __TITLE__: one question, yes or no, in Vue.
     The SDK is connected once, when the view mounts; what it hands over (the
     review, whether it is read-only, the draft) becomes reactive state. The
     app's hand-over button (or ⌘/Ctrl+Enter) sends `collect` and this view
     submits. Replace the template and handOver with your own.

     The SDK is on the window from the script tag in index.html; the types
     come from the package, so `review.payload` is your payload. -->
<script setup lang="ts">
import { Check, X } from "@lucide/vue";
import { onMounted, ref, watchEffect } from "vue";
import type { Review, Plugin } from "@forgeplane/pinrail-plugin/types";

type Payload = { message: string };
type Decision = { ok: boolean };
/** what is kept between reloads: the decision so far, answer still open */
type Draft = { ok: boolean | null };

const { Pinrail } = window;
const review = ref<Review<Payload, Decision> | null>(null);
const readonly = ref(false);
const draft = ref<Draft>({ ok: null });
const errors = ref("");
let plugin: Plugin<Payload, Decision>;

onMounted(() => {
  plugin = Pinrail.connect<Payload, Decision>({
    onInit(init) {
      review.value = init.review;
      readonly.value = init.readonly;
      const kept = init.draft as Draft | null;
      if (kept) draft.value = { ok: typeof kept.ok === "boolean" ? kept.ok : null };
    },
    onCollect() {
      const { ok } = draft.value;
      if (ok === null) {
        errors.value = "Choose yes or no first.";
        return;
      }
      plugin.submit({ ok });
    },
    onViolations(list) {
      errors.value = list.map((e) => `${e.path || "/"}: ${e.message}`).join("\n");
    },
    onSubmitted() {
      review.value = { ...plugin.review! };
      readonly.value = true;
    },
  });
});

function pick(value: boolean) {
  draft.value = { ok: draft.value.ok === value ? null : value };
  errors.value = "";
  plugin.draft(draft.value, { flush: true });
}

// what the app's hand-over button says follows the answer
watchEffect(() => {
  if (!review.value || readonly.value) return;
  const ok = draft.value.ok;
  plugin.status({ label: ok === null ? "Hand over" : `Hand over: ${ok ? "yes" : "no"}` });
});

const markdown = (source: string) => Pinrail.markdown(source);
</script>

<template>
  <p v-if="!review" class="plugin-content dim">waiting for the shell…</p>
  <main v-else class="plugin-content">
    <div v-html="markdown(review.payload.message)"></div>
    <p v-if="readonly && review.decision" class="dim">
      Decided: <b>{{ review.decision.data?.ok ? "yes" : "no" }}</b>
    </p>
    <!-- withdrawn or expired: nobody answered -->
    <p v-else-if="readonly" class="dim">Closed without a decision ({{ review.status }})</p>
    <template v-else>
      <div class="choice">
        <button type="button" class="btn" id="yes" :aria-pressed="draft.ok === true" @click="pick(true)">
          <Check /> Yes
        </button>
        <button type="button" class="btn" id="no" :aria-pressed="draft.ok === false" @click="pick(false)">
          <X /> No
        </button>
      </div>
      <div id="errors" class="errors">{{ errors }}</div>
    </template>
  </main>
</template>

// pinrail-plugin/templates/react/src/App.tsx
// __TITLE__: one question, yes or no, in React.
// The SDK is connected once, when the view mounts; what it hands over (the
// review, whether it is read-only, the draft) becomes state. The app's
// hand-over button (or ⌘/Ctrl+Enter) sends `collect` and this view submits.
// Replace the markup and handOver with your own.
//
// The SDK is on the window from the script tag in index.html; the types
// come from the package, so `review.payload` is your payload.
import { Check, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import type { Review, Plugin } from "@forgeplane/pinrail-plugin/types";

type Payload = { message: string };
type Decision = { ok: boolean };
/** what is kept between reloads: the decision so far, answer still open */
type Draft = { ok: boolean | null };

const { Pinrail } = window;

export function App() {
  const [review, setReview] = useState<Review<Payload, Decision> | null>(null);
  const [readonly, setReadonly] = useState(false);
  const [draft, setDraft] = useState<Draft>({ ok: null });
  const [errors, setErrors] = useState("");
  const plugin = useRef<Plugin<Payload, Decision> | null>(null);
  // the SDK's callbacks are made once, so they read the draft from here
  const latest = useRef(draft);
  latest.current = draft;

  useEffect(() => {
    plugin.current = Pinrail.connect<Payload, Decision>({
      onInit({ review, readonly, draft }) {
        setReview(review);
        setReadonly(readonly);
        const kept = draft as Draft | null;
        if (kept) setDraft({ ok: typeof kept.ok === "boolean" ? kept.ok : null });
      },
      onCollect() {
        const { ok } = latest.current;
        if (ok === null) return setErrors("Choose yes or no first.");
        plugin.current!.submit({ ok });
      },
      onViolations(errors) {
        setErrors(errors.map((e) => `${e.path || "/"}: ${e.message}`).join("\n"));
      },
      onSubmitted() {
        setReview({ ...plugin.current!.review! });
        setReadonly(true);
      },
    });
  }, []);

  // what the app's hand-over button says follows the answer
  useEffect(() => {
    if (!review || readonly) return;
    plugin.current!.status({ label: draft.ok === null ? "Hand over" : `Hand over: ${draft.ok ? "yes" : "no"}` });
  }, [review, readonly, draft.ok]);

  function pick(value: boolean) {
    const next = { ok: latest.current.ok === value ? null : value };
    setDraft(next);
    setErrors("");
    plugin.current!.draft(next, { flush: true });
  }

  if (!review) return <p className="plugin-content dim">waiting for the shell…</p>;
  const decided = review.decision?.data;
  return (
    <main className="plugin-content">
      <div dangerouslySetInnerHTML={{ __html: Pinrail.markdown(review.payload.message) }} />
      {readonly && decided ? (
        <p className="dim">
          Decided: <b>{decided.ok ? "yes" : "no"}</b>
        </p>
      ) : readonly ? (
        // withdrawn or expired: nobody answered
        <p className="dim">Closed without a decision ({review.status})</p>
      ) : (
        <>
          <div className="choice">
            <button type="button" className="btn" id="yes" aria-pressed={draft.ok === true} onClick={() => pick(true)}>
              <Check /> Yes
            </button>
            <button type="button" className="btn" id="no" aria-pressed={draft.ok === false} onClick={() => pick(false)}>
              <X /> No
            </button>
          </div>
          <div id="errors" className="errors">
            {errors}
          </div>
        </>
      )}
    </main>
  );
}
